### ISSUE TITLE
Add docker requirements in the docs for  seldon model in FfDL 

### ISSUE THREAD

**Issue by johnugeorge** [IBM/FfDL#112]
When image is built for seldon model using s2i, minimum required memory for docker is 8G. 

Add these details in https://github.com/IBM/FfDL/blob/master/community/FfDL-Seldon/pytorch-model/README.md

**Comment by Tomcli** [comment]
In the S2I instructions, we asked the users 
```
From the pytorch-model folder run the following s2i build. You will need to change seldonio to your Docker repo. You will need at least 8GB for your local Docker.
```

Perhaps we should make it more clear. (Bold the hard requirements). Thank you for pointing this out.
