### ISSUE TITLE
/ FfDL/demos/fashion-mnist-adversarial/README.md references internal repository

### ISSUE THREAD

**Issue by ptitzler** [IBM/FfDL#155]
Acknowledgements section:

> Special thanks to Anupama-Murthi and Vijay Arya who created the original notebook which we modified here to showcase how to use ART with FfDL. If you would like to try Watson Machine Learning (WML) Service with ART check out Anupama and Vijay's notebook here:
https://github.ibm.com/robust-dlaas/ART-in-WML/Use ART to check robustness of deep learning models.ipynb

The referenced notebook is not publicly accessible.

**Comment by Tomcli** [comment]
Fixed by #157 since the referenced notebook is not publicly available.
