### ISSUE TITLE
tiller-deploy is in status CrashLoopBackOff

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#162]
@Tomcli   If tiller-deploy is in status CrashLoopBackOff, not in running, but I run tiller manually, and after I run "helm install .", some pods are also on status CrashLoopBackOff, so I wander if tiller-deploy affect the installation of FfDL??? 
Thank you very much.

![_ _20190121191209](https://user-images.githubusercontent.com/24602893/51471064-a0c18f00-1db0-11e9-835b-4b287a364b49.png)

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, Tiller is the helm server which is responsible for properly deploying the FfDL helm chart. Can you check which version of Helm you are using? `helm version` and log the errors from the tiller pod? `kubectl logs tiller-deploy-fffbc59d4-qkhfb -n kube-system`.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  Thank you for kind reply, after I delete it and it started by itself, it is in status running. Log is following.

kubectl logs tiller-deploy-fffbc59d4-7vkt5 -n kube-system
[main] 2019/01/21 11:40:50 Starting Tiller v2.11.0 (tls=true)
[main] 2019/01/21 11:40:50 GRPC listening on :44134
[main] 2019/01/21 11:40:50 Probes listening on :44135
[main] 2019/01/21 11:40:50 Storage driver is ConfigMap
[main] 2019/01/21 11:40:50 Max history per release is 0
