### ISSUE TITLE
Confused about manifest.yml

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#164]
@Tomcli    I am confused about the number of gpus and learners, what I understand is each learner can use the number of gpus I set, eg:
![_ _20190305091226](https://user-images.githubusercontent.com/24602893/53773892-27789880-3f27-11e9-81c7-1981879429f6.png)
gpus is set 2, learners is also set 2, so each learner uses 2 gpus, 2 learners use 4 gpus, what I say is right?  If it is right, what I want to know is that each learner runs the same code for training, I mean each learner just runs independently and saves 2 different models (2 learners for training). 
    Or what I just say is wrong, although it has 2 learners, and each learner has 2 gpus, it will just save one model for the training job, I mean the training job uses 4 gpus for distributed training.
    I don't know which one is right or both are wrong.
    Can you explain the relationship between gpus and learners? 
    Thank you.

**Comment by animeshsingh** [comment]
@Eric-Zhang1990 there is support for minio client, so it doesn`t have to be cloud storage

**Comment by Eric-Zhang1990** [comment]
@Tomcli   Another question: when I use my own image and data (using host-mount) for caffe training, I find it spends a long time for just 100 iters, from the log I find it spends most time on data Transform、Prefetch batch, etc. I don't know how it works?  Also, I can't find the caffe model it saved, I just set 'snapshot_prefix: "./lenet"', I don't know which path I should set, can you tell me where the caffe model is? Thank you.
caffe gpu-manifest.yml:
![image](https://user-images.githubusercontent.com/24602893/53865525-5deb0c00-402a-11e9-99fd-42def9962ad2.png)
---------------------
caffe training logs:
![_ _20190306113512](https://user-images.githubusercontent.com/24602893/53865535-68a5a100-402a-11e9-81d7-9f0dd65446a3.png)
![_ _20190306113531](https://user-images.githubusercontent.com/24602893/53865586-7fe48e80-402a-11e9-8b17-962161eb6a5e.png)
![_ _20190306160158](https://user-images.githubusercontent.com/24602893/53865602-85da6f80-402a-11e9-9e3f-dc9c1fbd4948.png)

**Comment by Eric-Zhang1990** [comment]
@Tomcli   I find when I use s3 storage or host mount for caffe training, I can not find where caffe model is.  
1. s3 storage:
![_ _20190307085429](https://user-images.githubusercontent.com/24602893/53924395-e4e5c600-40b6-11e9-8660-35e858f96fb3.png)
2. host mount:
![_ _20190307084935](https://user-images.githubusercontent.com/24602893/53924388-e0b9a880-40b6-11e9-891d-29ceb5f940f3.png)
But when I use s3 storage or host mount for tensorflow training, I can find tf model in 's3://tf_trained_model' or in '/home/mount_test/tf-train/result/model' (host mount). 
1. s3 storage:
![_ _20190307085811](https://user-images.githubusercontent.com/24602893/53924486-38581400-40b7-11e9-88e0-9e27a5f864e9.png)
2. host mount:
![_ _20190307084834](https://user-images.githubusercontent.com/24602893/53924456-0d6dc000-40b7-11e9-9ea1-22bc628bc7e4.png)

Can you tell me where caffe model is saved? Thank you.
