### ISSUE TITLE
learner pod failed

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#165]
@Tomcli   I am running the examples FfDL provided, but they all failed. I don't know how to find where error is, can you help me, thanks.
First, FfDL is running correctly.
![_ _20190222164513](https://user-images.githubusercontent.com/24602893/53230306-59853180-36c1-11e9-8dd7-103f54cab9cf.png)
I create bucket and upload data to s3 bucket.
![_ _20190222164730](https://user-images.githubusercontent.com/24602893/53230447-a79a3500-36c1-11e9-8681-35e4753e3388.png)
![_ _20190222164531](https://user-images.githubusercontent.com/24602893/53230425-99e4af80-36c1-11e9-94b1-147f548bb13c.png)
![_ _20190222164207](https://user-images.githubusercontent.com/24602893/53230465-b08b0680-36c1-11e9-874e-ef21cfccdbb7.png)
I run "$CLI_CMD train etc/examples/tf-model/manifest.yml etc/examples/tf-model" or "$CLI_CMD train etc/examples/tf-model/gpu-manifest.yml etc/examples/tf-model", all get status FAILED.
![_ _20190222163944](https://user-images.githubusercontent.com/24602893/53230534-d9130080-36c1-11e9-962a-91518633d585.png)
And I find the data path is "source: "/mnt/data/tf_training_data/train/"" (lenet_train_test.prototxt) in caffe train. Is this path right?
Thank you!

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, did you update the manifest file with the correct object storage endpoint? In the instructions, if you are using the local object storage, the following script should help you setup the right endpoint
```
if [ "$(uname)" = "Darwin" ]; then
  sed -i '' s/s3.default.svc.cluster.local/$node_ip:$s3_port/ etc/examples/tf-model/manifest.yml
else
  sed -i s/s3.default.svc.cluster.local/$node_ip:$s3_port/ etc/examples/tf-model/manifest.yml
fi
```
Note you need to have `node_ip` and `s3_port` environment variable setup in your shell.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  I run command 'sed -i s/s3.default.svc.cluster.local/$node_ip:$s3_port/ etc/examples/tf-model/manifest.yml' to change the mainfest file, and it's status is Ok, but '$CLI_CMD show training-_S1ixBrmR' still shows status **Pending**, 
![_ _20190225154752](https://user-images.githubusercontent.com/24602893/53322244-c55fd800-3915-11e9-86d5-deb7bc6750cb.png)
-------------------------------------------
![_ _20190225155609](https://user-images.githubusercontent.com/24602893/53322730-3653bf80-3917-11e9-9f78-f28255121dee.png)
and I describe the pod 'learner', it shows:
![_ _20190225154720](https://user-images.githubusercontent.com/24602893/53322250-ca248c00-3915-11e9-8efa-51cac5ba619f.png)
What message "pod has unbound immediate PersistentVolumeClaims (repeated 3 times)" means?  
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   Seems I found error about above isuue, but I don't know wheather it is right or not.
I run 'kubectl get STORAGECLASS' and get:
![_ _20190225172524](https://user-images.githubusercontent.com/24602893/53327233-59d03780-3922-11e9-800a-1e86d3316f92.png)
So I change the file /FfDL/bin/create_static_volumes.sh (I don't know the change is right or not.)
![_ _20190225172632](https://user-images.githubusercontent.com/24602893/53327312-8421f500-3922-11e9-8135-ae2eda751b88.png)
I run 'kubectl get pvc --all-namespaces' and it is status is always 'pending', and 'kubectl describe pvc -n kube-system  static-volume-1' shows  message 'failed ***'.
![_ _20190225172003](https://user-images.githubusercontent.com/24602893/53327486-dcf18d80-3922-11e9-8587-e1f4678b9a21.png)
Can you help me analysis where the problem is? 
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  After I run 'FfDL/bin/create_static_pv.sh' and now status of 'static-volume-1' is Bound,
![_ _20190226200323](https://user-images.githubusercontent.com/24602893/53411715-311f6f00-3a02-11e9-9a40-6230fb87439c.png)
but I don't know how to modify the file tf-model/manifest.yaml, can you give me an detail example??
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli    I can run the example tf-model, but it still failed. Following is my logs.
[root@k8s-master FfDL]# $CLI_CMD logs training-sfDiYw9mR
Getting model training logs for 'training-sfDiYw9mR'...
Training with training/test data at:
  DATA_DIR: /job/tf_training_data
  MODEL_DIR: /job/model-code
  TRAINING_JOB: 
  TRAINING_COMMAND: python3 convolutional_network.py --trainImagesFile ${DATA_DIR}/train-images-idx3-ubyte.gz   --trainLabelsFile ${DATA_DIR}/train-labels-idx1-ubyte.gz --testImagesFile ${DATA_DIR}/t10k-images-idx3-ubyte.gz   --testLabelsFile ${DATA_DIR}/t10k-labels-idx1-ubyte.gz --learningRate 0.001   --trainingIters 2000 
Storing trained model at:
  RESULT_DIR: /job/tf_trained_model
Contents of $MODEL_DIR
total 44
drwxrwxrwx 2 6342627 root  256 Feb 27 07:14 .
drwxrwxrwx 6 root    root 4096 Feb 27  2019 ..
-rwxrwxrwx 1 6342627 root 7355 Jan 11 17:15 convolutional_network.py
-rwxrwxrwx 1 6342627 root 1129 Feb 26 10:43 gpu-manifest.yml
-rwxrwxrwx 1 6342627 root 5516 Jan 11 17:15 input_data.py
-rwxrwxrwx 1 6342627 root 1204 Jan 11 17:15 manifest-for-test.yml
-rwxrwxrwx 1 6342627 root 1611 Feb 27  2019 manifest-hostmount.yml
-rwxrwxrwx 1 6342627 root 1436 Feb 27  2019 manifest-hostmount.yml.bak
-rwxrwxrwx 1 6342627 root  957 Feb 25 10:33 manifest-nfs.yml
-rwxrwxrwx 1 6342627 root 1228 Feb 27  2019 manifest.yml
Contents of $DATA_DIR
total 1428
drwxr-xr-x 2 6342627 root    160 Feb 27 07:14 .
drwxrwxrwx 6 root    root   4096 Feb 27 07:14 ..
-rw-r--r-- 1 6342627 root 732947 Feb 27 06:50 t10k-images-idx3-ubyte.gz
-rw-r--r-- 1 6342627 root   4542 Feb 27 06:50 t10k-labels-idx1-ubyte.gz
-rw-r--r-- 1 6342627 root 683699 Feb 27 06:50 train-images-idx3-ubyte.gz
-rw-r--r-- 1 6342627 root  28881 Feb 27 06:50 train-labels-idx1-ubyte.gz
CHECKPOINT_DIR=
DATA_DIR=/job/tf_training_data
DOWNWARD_API_POD_NAME=learner-ee9b34a8-dc85-427c-5cab-737e7e247382-0
DOWNWARD_API_POD_NAMESPACE=kube-system
ELASTICSEARCH_PORT=tcp://10.109.88.121:9200
ELASTICSEARCH_PORT_9200_TCP=tcp://10.109.88.121:9200
ELASTICSEARCH_PORT_9200_TCP_ADDR=10.109.88.121
ELASTICSEARCH_PORT_9200_TCP_PORT=9200
ELASTICSEARCH_PORT_9200_TCP_PROTO=tcp
ELASTICSEARCH_SERVICE_HOST=10.109.88.121
ELASTICSEARCH_SERVICE_PORT=9200
ELASTICSEARCH_SERVICE_PORT_HTTP=9200
FFDL_LCM_PORT=tcp://10.100.84.102:80
FFDL_LCM_PORT_80_TCP=tcp://10.100.84.102:80
FFDL_LCM_PORT_80_TCP_ADDR=10.100.84.102
FFDL_LCM_PORT_80_TCP_PORT=80
FFDL_LCM_PORT_80_TCP_PROTO=tcp
FFDL_LCM_SERVICE_HOST=10.100.84.102
FFDL_LCM_SERVICE_PORT=80
FFDL_LCM_SERVICE_PORT_GRPC=80
FFDL_RESTAPI_PORT=tcp://10.104.197.17:80
FFDL_RESTAPI_PORT_80_TCP=tcp://10.104.197.17:80
FFDL_RESTAPI_PORT_80_TCP_ADDR=10.104.197.17
FFDL_RESTAPI_PORT_80_TCP_PORT=80
FFDL_RESTAPI_PORT_80_TCP_PROTO=tcp
FFDL_RESTAPI_SERVICE_HOST=10.104.197.17
FFDL_RESTAPI_SERVICE_PORT=80
FFDL_RESTAPI_SERVICE_PORT_FFDL=80
FFDL_TRAINER_PORT=tcp://10.96.205.221:80
FFDL_TRAINER_PORT_80_TCP=tcp://10.96.205.221:80
FFDL_TRAINER_PORT_80_TCP_ADDR=10.96.205.221
FFDL_TRAINER_PORT_80_TCP_PORT=80
FFDL_TRAINER_PORT_80_TCP_PROTO=tcp
FFDL_TRAINER_SERVICE_HOST=10.96.205.221
FFDL_TRAINER_SERVICE_PORT=80
FFDL_TRAINER_SERVICE_PORT_GRPC=80
FFDL_TRAININGDATA_PORT=tcp://10.97.135.76:80
FFDL_TRAININGDATA_PORT_80_TCP=tcp://10.97.135.76:80
FFDL_TRAININGDATA_PORT_80_TCP_ADDR=10.97.135.76
FFDL_TRAININGDATA_PORT_80_TCP_PORT=80
FFDL_TRAININGDATA_PORT_80_TCP_PROTO=tcp
FFDL_TRAININGDATA_SERVICE_HOST=10.97.135.76
FFDL_TRAININGDATA_SERVICE_PORT=80
FFDL_TRAININGDATA_SERVICE_PORT_GRPC=80
FFDL_UI_PORT=tcp://10.103.251.163:80
FFDL_UI_PORT_80_TCP=tcp://10.103.251.163:80
FFDL_UI_PORT_80_TCP_ADDR=10.103.251.163
FFDL_UI_PORT_80_TCP_PORT=80
FFDL_UI_PORT_80_TCP_PROTO=tcp
FFDL_UI_SERVICE_HOST=10.103.251.163
FFDL_UI_SERVICE_PORT=80
FFDL_UI_SERVICE_PORT_HTTP=80
GPU_COUNT=0.000000
HOME=/root
JOB_STATE_DIR=/job
KUBE_DNS_PORT=udp://10.96.0.10:53
KUBE_DNS_PORT_53_TCP=tcp://10.96.0.10:53
KUBE_DNS_PORT_53_TCP_ADDR=10.96.0.10
KUBE_DNS_PORT_53_TCP_PORT=53
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBE_DNS_PORT_53_UDP=udp://10.96.0.10:53
KUBE_DNS_PORT_53_UDP_ADDR=10.96.0.10
KUBE_DNS_PORT_53_UDP_PORT=53
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBE_DNS_SERVICE_HOST=10.96.0.10
KUBE_DNS_SERVICE_PORT=53
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
LEARNER_ID=1
LEARNER_NAME_PREFIX=learner-ee9b34a8-dc85-427c-5cab-737e7e247382
LOG_DIR=/job/logs
MODEL_DIR=/job/model-code
NUM_LEARNERS=1
OLDPWD=/notebooks
PATH=/usr/local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/job/model-code
PYTHONPATH=:/job/model-code
RESULT_BUCKET_DIR=
RESULT_DIR=/job/tf_trained_model
S3_PORT=tcp://10.100.44.197:80
S3_PORT_80_TCP=tcp://10.100.44.197:80
S3_PORT_80_TCP_ADDR=10.100.44.197
S3_PORT_80_TCP_PORT=80
S3_PORT_80_TCP_PROTO=tcp
S3_SERVICE_HOST=10.100.44.197
S3_SERVICE_PORT=80
SHLVL=3
TRAINING_COMMAND=python3 convolutional_network.py --trainImagesFile ${DATA_DIR}/train-images-idx3-ubyte.gz   --trainLabelsFile ${DATA_DIR}/train-labels-idx1-ubyte.gz --testImagesFile ${DATA_DIR}/t10k-images-idx3-ubyte.gz   --testLabelsFile ${DATA_DIR}/t10k-labels-idx1-ubyte.gz --learningRate 0.001   --trainingIters 2000 
TRAINING_ID=training-sfDiYw9mR
_=/usr/bin/env
Wed Feb 27 07:14:28 UTC 2019: Running training job
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Extracting /job/tf_training_data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "convolutional_network.py", line 64, in <module>
    train_labels_file, test_images_file, test_labels_file, one_hot=True)
  File "/job/model-code/input_data.py", line 137, in read_data_sets
    train_images = extract_images(TRAIN_IMAGES)
  File "/job/model-code/input_data.py", line 28, in extract_images
    buf = bytestream.read(rows * cols * num_images)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
Training process finished. Exit code: 1
Job exited with error code 1
Failed: learner_exit_code: 1

The error 'EOFError: Compressed file ended before the end-of-stream marker was reached' seems lile data is not completed, but I download minist data completely.
![image](https://user-images.githubusercontent.com/24602893/53474424-01c33d80-3aa8-11e9-8c57-48fe268e1c0e.png)
This is my manifest.yml file. I change the type form 'mount_cos' into 's3_datastore'.
![_ _20190227155619](https://user-images.githubusercontent.com/24602893/53474541-4e0e7d80-3aa8-11e9-93f1-a704e3809be7.png)

I don't know which step is wrong, can you help me?? 
Besides, can you provide me a method about how to use **NFS** for data using??
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   Now I can run the example tf-model (manifest.yml in cpu), however, I use the aws s3 storage to upload data for training, can you provide a method like NFS to storage data for training?? 
Thank you very much.

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, Sorry for the late reply. For the errors you have using the `mount_cos` mode, since you deploy the storage plugin with flag `cloud=false`. You need to install the s3fs driver and kubelet-plugin. (replace apt-get to yum if you are using CentOS)
```shell
sudo apt-get install s3fs
sudo mkdir -p /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ibmc-s3fs
sudo cp <FfDL repo>/bin/ibmc-s3fs /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ibmc-s3fs
sudo chmod +x /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ibmc-s3fs/ibmc-s3fs
sudo systemctl restart kubelet
```

@sboagibm can you describe how to use NFS as the data storage for FfDL training job? Thanks.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  Thank you for your kind reply. I have installed s3fs driver accoding to your steps, now I can run examples tf-model in cpu and gpu on one node by using s3 data storage, I will try it on multi nodes.

@sboagibm @Tomcli  I want to know how to use NFS on FfDL to use local data on our servers, thanks.

**Comment by sboagibm** [comment]
@Eric-Zhang1990 asked:
> I want to know how to use NFS on FfDL to use local data on our servers, thanks.

NFS is used internally for data sharing between the learner, helper, and job monitor pods.  It's not primarily involved in data access or results.  In fact, we're working on a re-architecture that gets rid of the need for NFS altogether.

To use local data directly you could try to enable a host mount at this time.  See the manifest at https://github.com/IBM/FfDL/blob/master/etc/examples/tf-model/manifest-hostmount.yml .

Maybe @fplk has other ideas on this front.  Not sure if there's any functioning options with using S3FS over minio or something.

There's hopefully some new code coming soon that will allow PVC mounts.  That's really what you want.

**Comment by Eric-Zhang1990** [comment]
@sboagibm   Host mount is also ok for me, but I don't know how to set the variable? like 'container:' 、 'connection:' , etc.  Can you give me a detail example? Thank you.
![_ _20190301090335](https://user-images.githubusercontent.com/24602893/53609363-90979d80-3c01-11e9-81a9-27b6c4450c31.png)

**Comment by sboagibm** [comment]
@Eric-Zhang1990 `connection/path` is the name of the directory you want to mount.  `training_data/container` is the name of a sub directory under the mount where the data will be fetched from.  `training_results/container` is the name of a sub directory under the mount where the training results will be written to.  You can see where these directories are set up for our test, and the permissions they need to have, at https://github.com/IBM/FfDL/blob/master/Makefile#L489.

Hope this helps!

**Comment by Eric-Zhang1990** [comment]
@sboagibm   I set these variables accoding to what you said above, 
![_ _20190301163137](https://user-images.githubusercontent.com/24602893/53626233-29e5a480-3c40-11e9-852a-836faf053fe4.png)
my data dir is like that:
![_ _20190301163803](https://user-images.githubusercontent.com/24602893/53626365-7d57f280-3c40-11e9-8408-fad5cca9f00e.png)
but the job still failed and log info is 'Failed: load_model_exit_code: 1', I don't know which step is wrong.
![_ _20190301163329](https://user-images.githubusercontent.com/24602893/53626259-3669fd00-3c40-11e9-8a44-c19e04430346.png)
Can you help me solve this?

**Comment by sboagibm** [comment]
@Eric-Zhang1990 Debugging this remotely is difficult.  My debugging strategy would be as follows.  Do a `watch kubectl get pods` so you can watch if/when the learner, helper, and job-monitor pods appear.  If the learner, helper, and job-monitor pods do not appear, log the lcm service and see if it's showing an error.  If the learner pod does appear, do an `kubectl exec -it learner-podname sh`,  go into the /cosdata directory, and see if all is as you expect.  Also do `kubectl logs learner-podname` and see if the learner is showing any interesting logs directly.

**Comment by Eric-Zhang1990** [comment]
@sboagibm    I run 'kubectl exec -it learner-podname sh' and go into '/mnt' directory, I can find the data, which is same as my host directory,
![_ _20190304174400](https://user-images.githubusercontent.com/24602893/53724667-4cc4c280-3ea5-11e9-86ea-e1948eefcf3d.png)
 but its log shows an error like that:
![_ _20190304174219](https://user-images.githubusercontent.com/24602893/53724678-51897680-3ea5-11e9-9506-061f67683155.png)
I did not find files about above directory, I run '$CLI_CMD train etc/examples/tf-model/manifest-hostmount.yml  etc/examples/tf-model.zip' to run training job.
Can you tell me some details about above error?
Thank you.

**Comment by Eric-Zhang1990** [comment]
@sboagibm   I create directory '_sbumitted_code' and copy 'model.zip' into it, now it can run correctly. Thank you for your reply.

**Comment by Eric-Zhang1990** [comment]
@Tomcli    I am confused about the number of gpus and learners, what I understand is each learner can use the number of gpus I set, eg:
![_ _20190305091226](https://user-images.githubusercontent.com/24602893/53773892-27789880-3f27-11e9-81c7-1981879429f6.png)
gpus is set 2, learners is also set 2, so each learner uses 2 gpus, 2 learners use 4 gpus, what I say is right?  If it is right, what I want to know is that each learner runs the same code for training, I mean each learner just runs independently and saves 2 different models (2 learners for training). 
    Or what I just say is wrong, although it has 2 learners, and each learner has 2 gpus, it will just save one model for the training job, I mean the training job uses 4 gpus for distributed training.
    I don't know which one is right or both are wrong.
    Can you explain the relationship between gpus and learners? 
    Thank you.

**Comment by Eric-Zhang1990** [comment]
@sboagibm   Now I can run job correctly, but after it completed, I can find the caffemodel it saved, can you tell me where the caffe model is? Thank you.
My config file:
![_ _20190305160945](https://user-images.githubusercontent.com/24602893/53790148-3a0fc380-3f61-11e9-9743-ec8aa818c186.png)
---------------------------
![_ _20190305161110](https://user-images.githubusercontent.com/24602893/53790185-51e74780-3f61-11e9-9a6e-cdda7365a13e.png)
![_ _20190305161021](https://user-images.githubusercontent.com/24602893/53790189-5449a180-3f61-11e9-81e6-5bcab6379a0a.png)

**Comment by sboagibm** [comment]
Should be in `/hom/mount_test/caffe-mnist/results`?

**Comment by Eric-Zhang1990** [comment]
@sboagibm   This is my directory content, I still can't fine caffe model.  One path I don't know how to set is 'snapshot_prefix: "./lenet"' in 'lenet_solver.prototxt'?  Can you provide an example you have used correctly?  Thank you.
![_ _20190306084756](https://user-images.githubusercontent.com/24602893/53847903-6cff9900-3fed-11e9-9440-68dcbcff9f55.png)

**Comment by Eric-Zhang1990** [comment]
> Should be in `/home/mount_test/caffe-mnist/results`?

@sboagibm   I find when I use s3 storage or host mount for caffe training, I can not find where caffe model is.  
![_ _20190307084935](https://user-images.githubusercontent.com/24602893/53924388-e0b9a880-40b6-11e9-891d-29ceb5f940f3.png)
-------------------
![_ _20190307085429](https://user-images.githubusercontent.com/24602893/53924395-e4e5c600-40b6-11e9-8660-35e858f96fb3.png)
But when I use s3 storage or host mount for tensorflow training, I can find tf model in 's3://tf_trained_model' or in '/home/mount_test/tf-train/result/model' (host mount). 
s3 storage:
![_ _20190307085811](https://user-images.githubusercontent.com/24602893/53924486-38581400-40b7-11e9-88e0-9e27a5f864e9.png)
host mount:
![_ _20190307084834](https://user-images.githubusercontent.com/24602893/53924456-0d6dc000-40b7-11e9-9ea1-22bc628bc7e4.png)

Can you tell me where caffe model is saved? Thank you.
