### ISSUE TITLE
caffe training speed  is very slow

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#166]
@Tomcli   Another question: when I use my own image and data (using host-mount) for caffe training, I find it spends a long time for just 100 iters, from the log I find it spends most time on data Transform、Prefetch batch, etc. I don't know how it works?   Thank you.
caffe gpu-manifest.yml:
![image](https://user-images.githubusercontent.com/24602893/53865525-5deb0c00-402a-11e9-99fd-42def9962ad2.png)
---------------------
caffe training logs:
![_ _20190306113512](https://user-images.githubusercontent.com/24602893/53865535-68a5a100-402a-11e9-81d7-9f0dd65446a3.png)
![_ _20190306113531](https://user-images.githubusercontent.com/24602893/53865586-7fe48e80-402a-11e9-8b17-962161eb6a5e.png)
![_ _20190306160158](https://user-images.githubusercontent.com/24602893/53865602-85da6f80-402a-11e9-9e3f-dc9c1fbd4948.png)

**Comment by Eric-Zhang1990** [comment]
@Tomcli    I am also confused about the number of gpus and learners, what I understand is each learner can use the number of gpus I set, eg:
![_ _20190305091226](https://user-images.githubusercontent.com/24602893/53773892-27789880-3f27-11e9-81c7-1981879429f6.png)
gpus is set 2, learners is also set 2, so each learner uses 2 gpus, 2 learners use 4 gpus, what I say is right?  If it is right, what I want to know is that each learner runs the same code for training, I mean each learner just runs independently and saves 2 different models (2 learners for training). 
    Or what I just say is wrong, although it has 2 learners, and each learner has 2 gpus, it will just save one model for the training job, I mean the training job uses 4 gpus for distributed training.
    I don't know which one is right or both are wrong.
    Can you explain the relationship between gpus and learners? 
    Thank you.

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, the bottleneck of your Caffe job is the CPU specs. With 0.5 CPU, preprocessing will take significantly more time than training the actual model. For our Caffe example running on GPU, I will recommend to put at least 2 cpus. 

For the manifest specs, you are correct that the amount of gpus, cpus, and memory on the manifest are for each learner. you can find the details of the manifest specs at https://github.com/IBM/FfDL/blob/master/docs/user-guide.md#24-creating-manifest-file

Thanks.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   Thank you for your kind reply. I see the info at https://github.com/IBM/FfDL/blob/master/docs/user-guide.md#24-creating-manifest-file, I also run multi learners for one training job, **what I am confused is if I use multi learners for one job, what I want to know is that the number of models I get is equal to number of learners, or although I use multi learners for one training job, I just get one model?**
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   Today I want to run   using FfDL, but I encounter the following error, do you have run some bigger project on FfDL successfully?
![深度截图_选择区域_20190312113240](https://user-images.githubusercontent.com/24602893/54172961-e64e2e80-44ba-11e9-84cf-16fc619c46c5.png)

**Comment by Eric-Zhang1990** [comment]
@Tomcli  I want to run maskrcnn-benchmark project (https://github.com/facebookresearch/maskrcnn-benchmark), 
![深度截图_选择区域_20190312171707](https://user-images.githubusercontent.com/24602893/54189345-8ec8b680-44ec-11e9-9199-1b4cd6f1dba8.png)
but I find NOTE in https://github.com/IBM/FfDL/blob/master/docs/user-guide.md#24-creating-manifest-file (Note that all model definition files has to be in the first level of the zip file and there are no nested directories in the zip file.), which means I can't run job which has multi directories, right?
However, all our projects have multi directories, how can I run them on FfDL?
Thank you.
