### ISSUE TITLE
distributed training questions

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#168]
@Tomcli  @sboagibm    Sorry about bothering you. 
I am still confused about multi learners. 
![深度截图_选择区域_20190318171958](https://user-images.githubusercontent.com/24602893/54519706-16f20480-49a2-11e9-84d7-250e8b97efb9.png)
What I understand is that multi learners mean distributed training, but when I run pytorch job using 3 learners (each learner has 1 gpu), I can get 3 training results, and they run independently.
![深度截图_选择区域_20190318170934](https://user-images.githubusercontent.com/24602893/54519720-1eb1a900-49a2-11e9-8263-d384afd5cd47.png)
------------------------------------------------
Which means I just run the same job on different servers, not distributed training, right?
Thank you.

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, we have examples on how to train distributed PyTorch on FfDL. https://github.com/IBM/FfDL/blob/master/etc/examples/c10d-native-parallelism/model-files/train_dist_parallel.py#L187-L227

On FfDL, all the learners will have a shared working directory under `/job/` path. We used that path to discover all the learner container's IP and connect them with 'gloo'/'nccl'/'mpi' protocols. Then during model training, we will average the gradient at the end of each batch for our example.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  Thank you for your kind reply.
