### ISSUE TITLE
why pytorch distributed training on two servers is slower than training on one server

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#169]
@Tomcli   I can run pytorch distributed training on multi nodes, but I find that speed of distributed training on two servers is slower than that on one server, I don't know why, can you help me see it deeply? Thank you.
----------------------------------------
I find that the number of "node_rank" is different between one server and two servers. One server has **2 "node_rank"**, but two servers just have **1 "node_rank"**.
This is result of training on one server. (2 gpus, each learner has one)
![深度截图_选择区域_20190326085510](https://user-images.githubusercontent.com/24602893/54964037-d1d36100-4fa5-11e9-80dd-ff1432a5ec2e.png)
------------------------------------------
![深度截图_选择区域_20190325165558](https://user-images.githubusercontent.com/24602893/54964070-fd564b80-4fa5-11e9-9ec3-83a2f34f15ea.png)
That is result of training on two servers. (2 gpus, each learner has one, but on two servers)
![深度截图_选择区域_20190326085438](https://user-images.githubusercontent.com/24602893/54964044-d8fa6f00-4fa5-11e9-819c-51e6cb877681.png)
-----------------------------------------
![深度截图_选择区域_20190325165801](https://user-images.githubusercontent.com/24602893/54907419-65624e80-4f20-11e9-907c-3a8a870619ad.png)

**Comment by Eric-Zhang1990** [comment]
@Tomcli   I run the example pytorch-launch-dist on two servers using **3 learners** (but there just has 2 Processes), 1 learner is on one server, and 2 learners are both on another server, but the log just has "node_rank=0" and "node_rank=1", there has no "node_rank=2", it is the same as my issue above. 
I wonder that is there no communication between the two servers?
![深度截图_选择区域_20190326154123](https://user-images.githubusercontent.com/24602893/54979246-a5d3d200-4fdd-11e9-8e96-ac08142b21d2.png)
![深度截图_选择区域_20190326154045](https://user-images.githubusercontent.com/24602893/54979249-a79d9580-4fdd-11e9-9bf7-94af06264474.png)
![深度截图_选择区域_20190326153424](https://user-images.githubusercontent.com/24602893/54979254-ab311c80-4fdd-11e9-98ba-ffcb262fff92.png)

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990 , It could be something has timed out when you initiating your process group due to low bandwidth. What protocol did you use for initiating your process group? Is it TCP, GLOO, or NCCL?

**Comment by Eric-Zhang1990** [comment]
@Tomcli   I try to use NCCL and GLOO, both of them have the same result above. Maybe it is caused by low bandwidth, I will continue to try. Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli    Now we use 1000M bandwidth, it can improve the training speed.
![深度截图_选择区域_20190328101741](https://user-images.githubusercontent.com/24602893/55124867-c10c2200-5142-11e9-9c65-aff9944915c0.png)
I wonder that which bandwidth do you use? Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli  Now we use 1000M bandwidth, I do a test for comparing the speed between using FfDL and just using system env (using conda) on the same server, I find that on the same setting, the training speed of just using system env  is faster than that of using FfDL.  I don't know why, do you know why? Thank you.
Using FfDL:
![FfDL---1-server-2-learners-each-1-gpu](https://user-images.githubusercontent.com/24602893/55134266-43a4d980-5163-11e9-8bd7-64936374d4f9.png)
Using system env (using conda):
![conda---1-server-2-gpus](https://user-images.githubusercontent.com/24602893/55134275-469fca00-5163-11e9-932a-d7d481e812dd.png)

**Comment by animeshsingh** [comment]
There is cost to be paid for bandwidth if you are spreading across two servers. What would be interesting is to see if both GPUs are on same server, it it faster than system env or not? Also the training has to be distributed across multiple GPUs I would say to override the payoff for bandwidth and extra communication overhead

**Comment by Eric-Zhang1990** [comment]
@animeshsingh    I have done some tests for comparing the speed between using FfDL and just using system env (using conda) on the same server, followings are the comparation:
**2 GPUs comparation:**
(a). Using system env, 2 gpus:
![conda---1-server-2-gpus](https://user-images.githubusercontent.com/24602893/55202093-eceddd00-5200-11e9-9368-045775162029.png)
(b). Using FfDL, 2 learners, each learner has 1 gpu:
![FfDL---1-server-2-learners-each-1-gpu](https://user-images.githubusercontent.com/24602893/55202127-1444aa00-5201-11e9-9705-5c2a63bd2dee.png)
(c). Using FfDL, 1 learner, this learner has 2 gpus:
![FfDL---1-server-1-learner-2-gpus](https://user-images.githubusercontent.com/24602893/55202146-258db680-5201-11e9-8174-baa99fccd89f.png)
**RESULT (> means faster)**: speed of a > speed of b > speed of c.
---------------------------------------------
**4 GPUs comparation:**
(d). Using system env, 4 gpus:
![conda---1-server-4-gpus](https://user-images.githubusercontent.com/24602893/55202101-f7a87200-5200-11e9-9a40-af680a948e6f.png)
(e). Using FfDL, 4 learners, each learner has 1 gpu:
![FfDL---1-server-4-learners-each-1-gpu](https://user-images.githubusercontent.com/24602893/55202694-6f779c00-5203-11e9-899d-6ed22d92a571.png)
(f). Using FfDL, 1 learner, this learner has 4 gpus:
![FfDL---1-server-1-learner-4-gpus](https://user-images.githubusercontent.com/24602893/55202274-b82e5580-5201-11e9-8e6a-4416dce32c4b.png)
**RESULT (> means faster)**: speed of d > speed of e > speed of f.
------------------------------------------
(All are on the same server) Also, when using system env, speed of 4 gpus is faster that of 2 gpus (it seems normal). However, when using FfDL, speed of 2 learners (each learner has 1 gpu, (c) above) is faster that that of 1 learner (this learner has 2 gpus, (b) above), and for 4 gpus, speed of 4 learners (each learner has 1 gpu, (e) above) is faster that that of 1 learner (this learner has 4 gpus, (f) above). 
**But** speed of 2 learners (each learner has 1 gpu, (c) above) is faster that that of 4 learners (each learner has 1 gpu, (e) above), it seems not normal.
------------------------------------------
Can you help me to explain above results? Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli @animeshsingh    I am running the project maskrcnn-benchmark (https://github.com/facebookresearch/maskrcnn-benchmark) on 3 nodes, 16 gpus(2 nodes have 4 gpus respectively, 1 node has 8 gpus). What I want to ask is that original code uses "torch.distributed.reduce()", but I am on multi nodes and multi GPUs, what should I use "torch.distributed.reduce_multigpu" or "torch.distributed.all_reduce_multigpu" or someone else? And will they affect the training speed? Because my training speed is very slow when I use 3 nodes and 16 gpus, just like comparation above.
Thank you.

**Comment by animeshsingh** [comment]
Thanks @Eric-Zhang1990 for testing this thoroughly. While using bare metal directly without the overhead of containers if we have the same number of GPUs, the speed is going to be faster on bare metal.

Going behind the concept of FfDL, the idea is to distribute training over multiple containers and the fact that these containers can be spawned and killed on demand. This allows multiple users to share the same hardware backend environment, and then be able to provide capabilities like batch scheduling, job queuing, moitoring etc which we are working towards adding by integrating with [kube-batch](https://github.com/kubernetes-sigs/kube-batch)

**Comment by animeshsingh** [comment]
> **But** speed of 2 learners (each learner has 1 gpu, (c) above) is faster that that of 4 learners (each learner has 1 gpu, (e) above), it seems not normal.
> Can you help me to explain above results? Thank you.

It definitely doesn`t seem normal, and we would like to simulate at our end and test more. Are these two GPUs in the first case on same machine, and while doing 4 GPUs we spread across two machines?

**Comment by animeshsingh** [comment]
> @Tomcli @animeshsingh I am running the project maskrcnn-benchmark (https://github.com/facebookresearch/maskrcnn-benchmark) on 3 nodes, 16 gpus(2 nodes have 4 gpus respectively, 1 node has 8 gpus). What I want to ask is that original code uses "torch.distributed.reduce()", but I am on multi nodes and multi GPUs, what should I use "torch.distributed.reduce_multigpu" or "torch.distributed.all_reduce_multigpu" or someone else? And will they affect the training speed? Because my training speed is very slow when I use 3 nodes and 16 gpus, just like comparation above.
> Thank you.

I would assume reduce should be faster, given that only the process with rank dst is going to receive the final result.
https://pytorch.org/docs/stable/distributed.html

**Comment by Eric-Zhang1990** [comment]
> > **But** speed of 2 learners (each learner has 1 gpu, (c) above) is faster that that of 4 learners (each learner has 1 gpu, (e) above), it seems not normal.
> > Can you help me to explain above results? Thank you.
> 
> It definitely doesn`t seem normal, and we would like to simulate at our end and test more. Are these two GPUs in the first case on same machine, and while doing 4 GPUs we spread across two machines?

Thanks @animeshsingh for kind reply. I test them on same machine (this machine has 4 gpus). I also think it is not normal, but I don't know which reason will cause this phenomenon. Just like I describe above, when I use 3 nodes, 16 gpus (16 learners on 3 machines), it is very slower than 4 learners (4 learners on same machine). 
What we think is speed of more gpus will be faster than less gpus, but it is inverse.

**Comment by Eric-Zhang1990** [comment]
@animeshsingh @Tomcli   When I see the doc "FfDL/docs/gpu-guide.md" again, it says that we should use "helm install --set lcm.device_plugin=false ." to deploy FfDL, but I didn't use parameter "lcm.device_plugin=false", does it affect the training speed?
Thank you.
![深度截图_选择区域_20190401155730](https://user-images.githubusercontent.com/24602893/55312278-b087de80-5497-11e9-9246-8e4fea0487af.png)

**Comment by animeshsingh** [comment]
> > > **But** speed of 2 learners (each learner has 1 gpu, (c) above) is faster that that of 4 learners (each learner has 1 gpu, (e) above), it seems not normal.
> > > Can you help me to explain above results? Thank you.
> > 
> > 
> > It definitely doesn`t seem normal, and we would like to simulate at our end and test more. Are these two GPUs in the first case on same machine, and while doing 4 GPUs we spread across two machines?
> 
> Thanks @animeshsingh for kind reply. I test them on same machine (this machine has 4 gpus). I also think it is not normal, but I don't know which reason will cause this phenomenon. Just like I describe above, when I use 3 nodes, 16 gpus (16 learners on 3 machines), it is very slower than 4 learners (4 learners on same machine).
> What we think is speed of more gpus will be faster than less gpus, but it is inverse.

On the same machine, more GPUs should definitely be faster. When going across machines, it depends on having the right combination for your hardware as described here
https://pytorch.org/docs/stable/distributed.html#which-backend-to-use

**Comment by Eric-Zhang1990** [comment]
@animeshsingh  I use 'nccl' backend and 'reduce' which original maskrcnn-benchmark provides, and when I run maskrcnn-benchmark on 2 machines just using pytorch distributed training (not using FfDL), I can run correctly using backend 'gloo', but error occurs when using 'nccl', I am still trying to find solution.

**Comment by Eric-Zhang1990** [comment]
@animeshsingh   Do you run the original maskrcnn-benchmark on FfDL?  How about the speed between multi gpus on one machine and multi gpus on two or more machines? Thank you.

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990, sorry for the late reply. Can you show us the commands and specs you used for running the maskrcnn-benchmark on FfDL? Is it similar to https://github.com/IBM/FfDL/blob/f6afd4cd87b8e272caa48f2d2ad3a40c31da451b/etc/examples/pytorch-launch-dist/manifest.yml#L50

And you specified 4 gpus and 3 learners? Thanks.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   My manifest .yml is similar to 'FfDL/etc/examples/pytorch-launch-dist/manifest.yml',
![深度截图_选择区域_20190408083324](https://user-images.githubusercontent.com/24602893/55692349-c0447d00-59d9-11e9-86e9-2f03c32f1824.png)
and my setup.sh is same as 'FfDL/etc/examples/pytorch-launch-dist/setup.sh'
![深度截图_选择区域_20190408083433](https://user-images.githubusercontent.com/24602893/55692351-c63a5e00-59d9-11e9-80a0-e653109876f9.png)
Can you help me to find  where the prblem is?
Thank you.

**Comment by Eric-Zhang1990** [comment]
@Tomcli   I do a test, I run the same code using FfDL and pytorch's distributed training directly, the speed of pytorch's distributed training is almost 2 times faster than FfDL, both of them are using the same machines and  GPUs.
FfDL:
![深度截图_选择区域_20190411092008](https://user-images.githubusercontent.com/24602893/55924247-aace8d80-5c3b-11e9-94dc-880e4351bf51.png)
pytorch's distributed training directly:
![深度截图_选择区域_20190410174535](https://user-images.githubusercontent.com/24602893/55924245-a5714300-5c3b-11e9-94c6-6fe9333ac0e5.png)
----------------------
Is it because some micro services running on FfDL? 
Thank you.

**Comment by animeshsingh** [comment]
@Eric-Zhang1990 Directly you are running on baremetal?

**Comment by Eric-Zhang1990** [comment]
@animeshsingh   Yeah, I run the maskrcnn-benchmark using conda env, the code and parameters are all the same, the command I use is following (2 machines, each one has 4 gpus):
Master:
NCCL_SOCKET_IFNAME=eno1 python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr="192.168.110.25" --master_port=1234 train_net.py
Node 1:
NCCL_SOCKET_IFNAME=enp129s0f0 python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="192.168.110.25" --master_port=1234 train_net.py
