### ISSUE TITLE
Adding support for Caffe2 and PyTorch

### ISSUE THREAD

**Issue by animeshsingh** [IBM/FfDL#17]
@Tomcli based on your investigation what`s needed on this side?

**Comment by Tomcli** [comment]
For CPU, simply add the new framework options and pull the images in the lcm/container_helper_extensions.go. Then we need to add some unit test and example jobs and should be good to go.

**Comment by Tomcli** [comment]
For GPU, they are on the same boat with Caffe and TensorFlow where we need to implement a trigger in LCM to switch the job between CPU and GPU seamlessly.

**Comment by Tomcli** [comment]
Fixed in #24
