### ISSUE TITLE
Add support to switch to GPU learner images seamlessly

### ISSUE THREAD

**Issue by Tomcli** [IBM/FfDL#20]
Currently we had a hard-coded solution to use GPU learner image with accelerator at the [gpu-dev](https://github.com/IBM/FfDL/blob/gpu-dev/docs/gpu-guide.md) branch. We will need to implement a trigger to pull the correct learner image without using the hard-coded solution.

**Comment by animeshsingh** [comment]
@Tomcli i think they key thing I am looking for is what changes I need to do in the code to configure FfDL to run GPU jobs. Lets dump those manual instructions here

**Comment by animeshsingh** [comment]
@Tomcli can we close this now?

**Comment by Tomcli** [comment]
Fixed in #24
