### ISSUE TITLE
Readiness probe failed

### ISSUE THREAD

**Issue by ZhengRongTan** [IBM/FfDL#48]
the pod prometheus' status is CrashLoopBackOfff

Readiness probe failed: Get http://192.168.7.81:3000/api/health: dial tcp 192.168.7.81:3000: getsockopt: connection refused

**Comment by ZhengRongTan** [comment]
error log as below :
Failed to send requesterrorGet https://grafana.com/api/plugins/repo/grafana-piechart-panel: dial tcp 107.178.222.220:443: getsockopt: connection timed out
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/grafana-piechart-panel: dial tcp 107.178.222.220:443: getsockopt: connection timed out
NAME:
   Grafana cli plugins install - install &lt;plugin id&gt; &lt;plugin version (optional)&gt;
USAGE:
   Grafana cli plugins install [arguments...

**Comment by ZhengRongTan** [comment]
And my k8s cluster can not access the internet !!

**Comment by ZhengRongTan** [comment]
manually build grafana image ; fixed;

**Comment by Eric-Zhang1990** [comment]
@ZhengRongTan  I have the same issue as you, how do you manually build grafana image? Thanks.
