### ISSUE TITLE
Learner Issue - ffdl/ffdl-controller not found

### ISSUE THREAD

**Issue by Tomcli** [IBM/FfDL#6]
The Learner requires the ffdl-controller image and apparently is not available on the Public DockerHub. 

Also, log-collector images (e.g. ffdl/tensorboard_extract_1.3-py3:latest) also not available on DockerHub.

**Comment by animeshsingh** [comment]
@Tomcli how are the tests passing?

**Comment by whummer** [comment]
Thanks for reporting @Tomcli 

@animeshsingh The builds are passing because we're building the images locally (we don't pull them from Docker hub at this point)

**Comment by animeshsingh** [comment]
Thanks - maybe we should extend the test to also deploy pulling from docker hub - that`s what most of the users will do

**Comment by whummer** [comment]
Agreed, and we should also set up the build to push the `latest` images to Docker hub. (we need to introduce proper image versioning at some point).

@Tomcli images are pushed - can you give it another try now please? Thanks

**Comment by Tomcli** [comment]
@whummer Just tested with the tf-model job and it completed. However, the caffe-model job failed during the processing stage with
```
I0212 18:15:07.998613    66 layer_factory.hpp:77] Creating layer mnist
F0212 18:15:07.998891    66 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x155096d2f5cd  google::LogMessage::Fail()
    @     0x155096d31433  google::LogMessage::SendToLog()
    @     0x155096d2f15b  google::LogMessage::Flush()
    @     0x155096d31e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x1550972d6d88  caffe::db::LMDB::Open()
    @     0x1550973a6d1f  caffe::DataLayer<>::DataLayer()
    @     0x1550973a6eb2  caffe::Creator_DataLayer<>()
    @     0x1550972a1a40  caffe::Net<>::Init()
    @     0x1550972a455e  caffe::Net<>::Net()
    @     0x155097283a85  caffe::Solver<>::InitTrainNet()
    @     0x155097284ef5  caffe::Solver<>::Init()
    @     0x15509728520f  caffe::Solver<>::Solver()
    @     0x1550972732a1  caffe::Creator_SGDSolver<>()
    @           0x40b791  train()
    @           0x4080f0  main
    @     0x155095c81830  __libc_start_main
    @           0x408919  _start
    @              (nil)  (unknown)
```

It looks like the issue is from the caffe example itself. So I think is images issue is resolved and we can open a new issue for the caffe example job.

**Comment by datamonday** [comment]
I met this same error,could u tell me what should i do? thanks!

**Comment by animeshsingh** [comment]
@Tomcli please check it.

**Comment by Tomcli** [comment]
Hi @datamonday, did you deploy FfDL on Minikube or on a proper Kubernetes Cluster?
