### ISSUE TITLE
helm install issue with one pod getting into CrashLoopBackOff 

### ISSUE THREAD

**Issue by lingarajonline** [IBM/FfDL#61]
I am getting error with one pod that gets into CrashLoopBackoff status. I have tried a few times with clean 'helm install' but get the same error.

ffdl-trainingdata-86c5578b75-v884m 0/1 CrashLoopBackOff 

<img width="1663" alt="screen shot 2018-04-09 at 6 30 42 pm" src="https://user-images.githubusercontent.com/34495576/38536978-e5760a56-3c40-11e8-81c3-6d94fd105485.png">
5 7m

Any suggestion, how to get past this error and have a clean deployment of this fabric? Thanks

**Comment by lingarajonline** [comment]
Hi @Tomcli, all other pods are running fine, except this ffdl-trainindata
<img width="831" alt="screen shot 2018-04-10 at 9 29 06 am" src="https://user-images.githubusercontent.com/34495576/38570099-dad6a572-3ca1-11e8-8135-8ec5474841cb.png">

**Comment by Tomcli** [comment]
What happen if you do `kubectl delete pod ffdl-trainingdata-86c5578b75-v884m` and let the replicaset roll out a new pod?

**Comment by lingarajonline** [comment]
new pod also gets into the same CrashLoopBackOff state. Btw, I am running these with IBM Cloud Kubernetes ( not minikube).. not sure if this is K8s env specific?
<img width="762" alt="screen shot 2018-04-10 at 9 59 51 am" src="https://user-images.githubusercontent.com/34495576/38571851-7c798896-3ca6-11e8-9e15-56c11149566f.png">
<img width="834" alt="screen shot 2018-04-10 at 10 01 53 am" src="https://user-images.githubusercontent.com/34495576/38571852-7c9391be-3ca6-11e8-8bee-f3ad7f931c0d.png">

**Comment by Tomcli** [comment]
IBM Cloud should work the same as Minikube. Looks like your ffdl-trainingdata is trying to create an existing index `dlaas_learner_data`, it shouldn't happen based on the code. What I could think of now is either there's a bug for a specific k8s version or the elastic search is complaining for insufficient memory.

What is your K8s cluster version and spec? Can you log your `storage-0` and grep `dlaas_learner_data` to see is there any error?

**Comment by lingarajonline** [comment]
Hi @Tomcli, Thanks for giving some hints on the version. The K8s cluster version at IBM Cloud is Ok, but my kubectl client version was ahead of the IBM K8s cluster. Downgraded the client version to match the server version and re-install helm chart. Now all PODs are running.
